const Forms=(()=>{
  const H=Hotel,O=Operations,E=H.esc,M=H.money;
  const actor=()=>Auth.current(),state=()=>H.data;
  const dt=value=>value?new Date(value).toLocaleString('es-BO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
  const staff=id=>state().employees.find(e=>e.id===id)?.name||'Usuario';
  const field=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;
  const option=(value,label,selected)=>`<option value="${E(value)}" ${String(value)===String(selected)?'selected':''}>${E(label)}</option>`;
  const select=(label,name,options)=>`<label>${label}<select name="${name}" required>${options}</select></label>`;
  const note=(name,value='',label='Observaciones')=>`<label>${label}<textarea name="${name}" rows="3" maxlength="1000">${E(value)}</textarea></label>`;
  const head=(title,description='')=>`<button class="modal-close icon-btn" data-close-modal aria-label="Cerrar">${Icon('close')}</button><h2>${E(title)}</h2>${description?`<p class="modal-description">${E(description)}</p>`:''}`;
  function show(title,description,content,wide=false){H.showModal(`<div class="modal-body">${head(title,description)}${content}</div>`);if(wide)document.querySelector('.modal-panel').classList.add('wide');}
  function form(title,description,content,save,label='Guardar',wide=false){
    show(title,description,`<form class="modal-form">${content}<p class="form-error" role="alert" id="form-error"></p><div class="modal-actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancelar</button><button class="btn btn-primary" type="submit">${label}</button></div></form>`,wide);
    const f=document.querySelector('.modal-form');f.addEventListener('submit',e=>{e.preventDefault();const err=f.querySelector('#form-error');err.textContent='';try{save(Object.fromEntries(new FormData(f)),f);}catch(error){err.textContent=error.message;err.scrollIntoView({block:'nearest'});}});return f;
  }
  function done(message){H.closeModal();window.dispatchEvent(new Event('hotel:updated'));H.toast(message);}
  function confirm(title,description,action){form(title,description,'',()=>{action();done('Operación realizada.');},'Confirmar');}
  function guest(id){const g=state().clients.find(x=>x.id===id)||{};form(id?'Editar huésped':'Registrar huésped','Datos de contacto e identificación.',`<div class="form-grid">${field('Nombre completo','name',g.name,'text','required minlength="3" autocomplete="name"')}${field('Documento / pasaporte','document',g.document,'text','required minlength="3"')}${field('Teléfono','phone',g.phone,'tel','required minlength="6" autocomplete="tel"')}${field('Correo electrónico','email',g.email,'email','autocomplete="email"')}${field('País','country',g.country||'Bolivia','text','required')}</div>`,v=>{O.saveGuest(actor(),v,id);done('Huésped guardado.');});}
  function booking(id,roomId='',date=''){
    const b=state().bookings.find(x=>x.id===id)||{};
    let start=b.start||(date?`${date}T${state().settings.checkin||'15:00'}`:O.local()),end=b.end||O.addHours(start,24);
    const rooms=state().rooms,room=rooms.find(r=>r.id===(b.roomId||roomId))||rooms.find(r=>O.available(state(),r.id,start,end))||rooms[0];
    const roomOptions=rooms.map(r=>option(r.id,`${r.number} · ${H.type(r.type)?.name||r.type} · ${M(O.rate(state(),r))}`,room?.id)).join('');
    const guestOptions=option('','Seleccionar huésped',b.guestId)+state().clients.map(g=>option(g.id,`${g.name}${g.document?' · '+g.document:''}`,b.guestId)).join('')+option('new','+ Registrar nuevo huésped');
    const f=form(id?'Editar reserva':'Nueva reserva','Define la estancia. La disponibilidad se comprueba antes de guardar.',`<div class="form-grid">${select('Habitación','roomId',roomOptions)}${select('Huésped','guestId',guestOptions)}</div><div id="new-guest-fields" hidden><p class="section-label">NUEVO HUÉSPED</p><div class="form-grid">${field('Nombre completo','guestName','','text','minlength="3"')}${field('Documento / pasaporte','guestDocument','','text','minlength="3"')}${field('Teléfono','guestPhone','','tel','minlength="6"')}${field('Correo (opcional)','guestEmail','','email')}</div></div><div class="form-grid">${field('Entrada','start',start,'datetime-local','required')}${field('Salida estimada','end',end,'datetime-local','required')}</div><div><p class="section-label">DURACIÓN RÁPIDA</p><div class="duration-options"><button type="button" class="btn btn-subtle btn-small" data-hours="3">3 horas</button><button type="button" class="btn btn-subtle btn-small" data-hours="6">6 horas</button><button type="button" class="btn btn-subtle btn-small" data-hours="24">1 día</button><button type="button" class="btn btn-subtle btn-small" data-hours="48">2 días</button><button type="button" class="btn btn-subtle btn-small" data-hours="72">3 días</button></div></div><p class="notice" id="availability" aria-live="polite"></p><div class="form-grid">${field('Huéspedes','guests',b.guests||1,'number','required min="1" step="1"')}${select('Estado','status',(b.status==='Hospedado'?['Hospedado']:O.activeStatuses).map(s=>option(s,s,b.status||'Confirmada')).join(''))}${field('Precio total (Bs)','price',b.price??O.rate(state(),room),'number','required min="0.01" step="0.01"')}<p class="form-help">La sugerencia usa la tarifa por día. Puedes ajustar el precio total para estancias cortas.</p></div>${note('notes',b.notes)}`,v=>{const input={...v};if(v.guestId==='new')input.newGuest={name:v.guestName,document:v.guestDocument,phone:v.guestPhone,email:v.guestEmail};O.saveBooking(actor(),input,id);done(id?'Reserva actualizada.':'Reserva registrada.');},id?'Guardar cambios':'Crear reserva',true);
    const update=(price=false)=>{const v=Object.fromEntries(new FormData(f)),r=H.room(v.roomId),hours=(new Date(v.end)-new Date(v.start))/3600000,available=hours>0&&O.available(state(),r.id,v.start,v.end,id);const box=f.querySelector('#availability');box.className=`notice ${available?'':'warning'}`;box.textContent=available?`Disponible · ${O.round(hours)} horas · Máximo ${H.type(r.type)?.capacity||2} huéspedes`:'La habitación no está disponible para ese intervalo. Cambia las fechas o la habitación.';f.elements.guests.max=H.type(r.type)?.capacity||2;if(price&&hours>0)f.elements.price.value=O.rate(state(),r)*Math.max(1,Math.ceil(hours/24));};
    ['roomId','start','end'].forEach(n=>f.elements[n].addEventListener('change',()=>update(true)));
    f.querySelectorAll('[data-hours]').forEach(btn=>btn.addEventListener('click',()=>{f.elements.end.value=O.addHours(f.elements.start.value,Number(btn.dataset.hours));update(true);}));
    f.elements.guestId.addEventListener('change',()=>{const box=f.querySelector('#new-guest-fields'),isNew=f.elements.guestId.value==='new';box.hidden=!isNew;box.querySelectorAll('input').forEach(el=>{el.disabled=!isNew;el.required=isNew&&el.type!=='email';});});f.elements.guestId.dispatchEvent(new Event('change'));update();
  }
  function bookingDetail(id){const b=state().bookings.find(x=>x.id===id);if(!b)return;const r=H.room(b.roomId),g=H.client(b.guestId),pending=O.balance(state(),id),active=O.activeStatuses.includes(b.status);
    show(`Habitación ${r.number}`,`${b.id} · ${b.status}`,`<div class="details-list"><div><span>Huésped</span><strong>${E(g?.name)}</strong></div><div><span>Entrada</span><strong>${dt(b.start)}</strong></div><div><span>Salida estimada</span><strong>${dt(b.end)}</strong></div><div><span>Duración</span><strong>${O.round((new Date(b.end)-new Date(b.start))/3600000)} horas · ${b.guests} huésped(es)</strong></div><div><span>Precio total</span><strong>${M(b.price)}</strong></div><div><span>Pagado</span><strong>${M(b.price-pending)}</strong></div><div><span>Saldo pendiente</span><strong class="${pending>0?'negative':'positive'}">${M(pending)}</strong></div></div>${b.notes?`<p class="notes-box">${E(b.notes)}</p>`:''}<div class="modal-actions wrap-actions">${active?`<button class="btn btn-secondary" data-action="edit-booking" data-id="${E(id)}">${Icon('edit')} Editar</button>`:''}${active&&pending>0?`<button class="btn btn-primary" data-action="charge" data-id="${E(id)}">Registrar cobro</button>`:''}${['Pendiente','Confirmada'].includes(b.status)?`<button class="btn btn-primary" data-action="checkin" data-id="${E(id)}">Registrar ingreso</button><button class="btn btn-danger" data-action="cancel-booking" data-id="${E(id)}">Cancelar reserva</button>`:''}${b.status==='Hospedado'?`<button class="btn btn-primary" data-action="checkout" data-id="${E(id)}">Registrar salida</button>`:''}</div>`);
  }
  function room(id){const r=H.room(id)||{};const f=form(id?`Editar habitación ${r.number}`:'Nueva habitación','La ocupación y las reservas se actualizan automáticamente.',`<div class="form-grid">${field('Número','number',r.number,'text','required maxlength="8"')}${select('Tipo','type',state().roomTypes.map(t=>option(t.id,t.name,r.type)).join(''))}${field('Tarifa por día (Bs)','price',r.price||520,'number','required min="0.01" step="0.01"')}${select('Estado operativo','baseStatus',['Disponible','Mantenimiento'].map(s=>option(s,s,r.baseStatus)).join(''))}</div>${id?'<button type="button" class="btn btn-danger" id="remove-room">Eliminar habitación sin historial</button>':''}`,v=>{O.saveRoom(actor(),v,id);done('Habitación guardada.');});if(!id)f.elements.type.addEventListener('change',()=>f.elements.price.value=H.type(f.elements.type.value).price);f.querySelector('#remove-room')?.addEventListener('click',()=>confirm('Eliminar habitación',`Se eliminará la habitación ${r.number} si no tiene historial.`,()=>O.removeRoom(actor(),id)));}
  function product(id){const p=state().products.find(x=>x.id===id)||{};form(id?'Editar producto':'Nuevo producto','Organiza los productos que vende el hotel.',`<div class="form-grid">${field('Nombre','name',p.name,'text','required minlength="2"')}${field('Categoría','category',p.category||'Bebidas','text','required list="categories"')}<datalist id="categories">${[...new Set(state().products.map(p=>p.category))].map(c=>`<option value="${E(c)}">`).join('')}</datalist>${field('Precio (Bs)','price',p.price||'','number','required min="0.01" step="0.01"')}${field('Stock mínimo','minStock',p.minStock??5,'number','required min="0" step="1"')}${!id?field('Stock inicial','stock',0,'number','required min="0" step="1"'):''}${select('Estado','active',option('1','Activo',p.active===false?'0':'1')+option('0','Inactivo',p.active===false?'0':'1'))}</div>`,v=>{O.saveProduct(actor(),{...v,active:v.active==='1'},id);done('Producto guardado.');});}
  function stock(id){const p=state().products.find(x=>x.id===id);form('Movimiento de inventario',`${p.name} · ${p.stock} unidades disponibles`,`${select('Movimiento','type',option('Entrada','Entrada de stock')+option('Salida','Salida / ajuste'))}${field('Cantidad','quantity',1,'number','required min="1" step="1"')}${field('Motivo','concept','','text','required minlength="3" placeholder="Ej. Reposición de proveedor"')}`,v=>{O.stockMove(actor(),{...v,productId:id});done('Inventario actualizado.');});}
  function sale(bookingId='',productId=''){
    const shift=state().shifts.find(s=>s.userId===actor().id&&s.status==='Abierta');if(!shift){form('Abre tu caja primero','Cada venta debe estar asociada a tu turno.',`<p class="notice">Registra el efectivo inicial para comenzar a vender.</p>`,()=>openShift(),'Abrir caja');return;}
    let type=bookingId?'room':'product';
    const f=form('Registrar venta',`Turno ${shift.id} · ${staff(actor().id)}`,`<div class="sale-type-tabs"><button type="button" data-sale-type="product">Productos</button><button type="button" data-sale-type="room">Habitación</button><button type="button" data-sale-type="other">Otro concepto</button></div><div id="sale-fields"></div>${select('Forma de pago','method',['Efectivo','Tarjeta','Transferencia'].map(s=>option(s,s)).join(''))}<div class="form-summary"><span>Total a cobrar</span><strong id="sale-total">${M(0)}</strong></div>`,(v)=>{let lines=[];if(type==='product')lines=[...f.querySelectorAll('.cart-line')].map(row=>({type,productId:row.querySelector('select').value,quantity:row.querySelector('input').value}));else if(type==='room')lines=[{type,bookingId:v.bookingId,quantity:1,unitPrice:v.amount}];else lines=[{type,description:v.description,quantity:1,unitPrice:v.amount}];const id=O.recordSale(actor(),{method:v.method,lines});done('Venta registrada e inventario actualizado.');saleDetail(id);},'Registrar venta');
    const productOptions=selected=>state().products.filter(p=>p.active&&p.stock>0).map(p=>option(p.id,`${p.name} · ${M(p.price)} · ${p.stock} disp.`,selected)).join('');
    function total(){let value=0;if(type==='product')f.querySelectorAll('.cart-line').forEach(row=>{const p=state().products.find(p=>p.id===row.querySelector('select').value);value+=(p?.price||0)*Number(row.querySelector('input').value||0);});else value=Number(f.elements.amount?.value||0);f.querySelector('#sale-total').textContent=M(value);}
    function addLine(selected){const options=productOptions(selected);if(!options)return;const row=document.createElement('div');row.className='cart-line';row.innerHTML=`<label>Producto<select required aria-label="Producto de la venta">${options}</select></label><label>Cant.<input type="number" min="1" step="1" value="1" required aria-label="Cantidad"></label><button type="button" class="icon-btn" aria-label="Quitar producto">${Icon('close',16)}</button>`;f.querySelector('.cart-lines').append(row);row.querySelector('button').addEventListener('click',()=>{row.remove();total();});total();}
    function renderType(){f.querySelectorAll('[data-sale-type]').forEach(b=>b.classList.toggle('active',b.dataset.saleType===type));const box=f.querySelector('#sale-fields');if(type==='product'){box.innerHTML=productOptions()?'<div class="cart-lines"></div><button type="button" class="btn btn-subtle btn-small section-space" id="add-sale-product">+ Agregar producto</button>':'<p class="notice warning">No hay productos activos con stock.</p>';if(productOptions()){addLine(productId);f.querySelector('#add-sale-product').addEventListener('click',()=>addLine());}}else if(type==='room'){const bookings=state().bookings.filter(b=>O.activeStatuses.includes(b.status)&&O.balance(state(),b.id)>0);box.innerHTML=bookings.length?`<div class="form-stack">${select('Estancia por cobrar','bookingId',bookings.map(b=>option(b.id,`Hab. ${H.room(b.roomId)?.number} · ${H.client(b.guestId)?.name} · Saldo ${M(O.balance(state(),b.id))}`,bookingId)).join(''))}${field('Importe a cobrar (Bs)','amount',O.balance(state(),bookingId||bookings[0].id),'number','required min="0.01" step="0.01"')}<p class="form-help">Puedes cobrar el saldo completo o un pago parcial.</p></div>`:'<p class="notice">No hay estancias con saldo pendiente.</p>';if(bookings.length)f.elements.bookingId.addEventListener('change',()=>{f.elements.amount.value=O.balance(state(),f.elements.bookingId.value);total();});}else box.innerHTML=`<div class="form-stack">${field('Concepto','description','','text','required minlength="3" placeholder="Ej. Lavandería"')}${field('Importe (Bs)','amount','','number','required min="0.01" step="0.01"')}</div>`;total();}
    f.querySelectorAll('[data-sale-type]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.saleType;renderType();}));f.addEventListener('input',total);f.addEventListener('change',total);renderType();
  }
  function saleDetail(id){const s=state().sales.find(x=>x.id===id);if(!s||(!Auth.isAdmin()&&s.userId!==actor().id))return;show('Detalle de venta',`${s.id} · ${dt(s.date)}`,`<div class="details-list"><div><span>Responsable</span><strong>${E(staff(s.userId))}</strong></div><div><span>Turno</span><strong>${E(s.shiftId)}</strong></div><div><span>Pago</span><strong>${E(s.method)}</strong></div></div>${s.lines.map(l=>`<div class="receipt-line"><span>${E(l.description)}<small>${l.quantity} × ${M(l.unitPrice)}</small></span><strong>${M(l.quantity*l.unitPrice)}</strong></div>`).join('')}<div class="receipt-total"><span>Total</span><strong>${M(s.total)}</strong></div>`);}
  function openShift(){form('Abrir caja','Cuenta el efectivo con el que comienza tu turno.',`${field('Efectivo inicial (Bs)','initial','','number','required min="0" step="0.01" placeholder="0.00"')}<p class="notice">Las ventas quedarán asociadas a ${E(actor().name)} y a este turno.</p>`,v=>{O.openShift(actor(),v.initial);done('Tu caja está abierta. Ya puedes registrar ventas.');location.hash='cajas';},'Abrir mi caja');}
  function cashMove(id){form('Movimiento de caja','Registra efectivo que entra o sale fuera de las ventas.',`${select('Tipo de movimiento','type',option('Egreso','Egreso de efectivo')+option('Ingreso','Ingreso de efectivo'))}${field('Importe (Bs)','amount','','number','required min="0.01" step="0.01"')}${field('Concepto','concept','','text','required minlength="3" placeholder="Ej. Compra de limpieza"')}`,v=>{O.cashMove(actor(),{...v,shiftId:id});done('Movimiento registrado.');});}
  const summaryHTML=(s,q)=>`<div class="shift-summary-grid"><div><span>Monto inicial</span><strong>${M(s.initial)}</strong></div><div><span>Total de ventas</span><strong>${M(q.total)}</strong></div><div><span>Ventas en efectivo</span><strong>${M(q.cash)}</strong></div><div><span>Tarjeta + transferencia</span><strong>${M(q.card+q.transfer)}</strong></div></div><div class="receipt-line"><span>Otros ingresos / egresos</span><strong>+ ${M(q.incoming)} / − ${M(q.outgoing)}</strong></div><div class="receipt-total"><span>Efectivo esperado</span><strong>${M(q.expected)}</strong></div>`;
  function closeShift(id){const s=state().shifts.find(x=>x.id===id),q=O.shiftSummary(state(),s);const f=form('Cerrar caja',`${staff(s.userId)} · Abierta ${dt(s.openedAt)}`,`${summaryHTML(s,q)}${field('Efectivo contado (Bs)','declared','','number','required min="0" step="0.01" placeholder="Cuenta el efectivo y escribe el total"')}<p id="cash-difference" class="notice" aria-live="polite">Introduce el efectivo contado para conciliar la caja.</p>${note('notes','','Observaciones del cierre')}<p class="form-help">El cierre es definitivo. Las ventas nuevas requerirán otro turno.</p>`,v=>{O.closeShift(actor(),id,v.declared,v.notes);done('Caja cerrada. El reporte PDF está disponible.');shiftDetail(id);},'Confirmar cierre');f.elements.declared.addEventListener('input',()=>{const diff=O.round(Number(f.elements.declared.value)-q.expected);f.querySelector('#cash-difference').textContent=diff===0?'Caja conciliada · sin diferencia':`${diff>0?'Sobrante':'Faltante'}: ${M(Math.abs(diff))} · explica el motivo.`;f.querySelector('#cash-difference').classList.toggle('warning',diff!==0);f.elements.notes.required=diff!==0;});}
  function shiftDetail(id){const s=state().shifts.find(x=>x.id===id);if(!s||(!Auth.isAdmin()&&s.userId!==actor().id))return;const q=O.shiftSummary(state(),s);show(`Caja ${s.status.toLowerCase()}`,`${staff(s.userId)} · ${s.id}`,`<div class="details-list"><div><span>Apertura</span><strong>${dt(s.openedAt)}</strong></div><div><span>Cierre</span><strong>${dt(s.closedAt)}</strong></div></div>${summaryHTML(s,q)}${s.status==='Cerrada'?`<div class="receipt-line"><span>Efectivo declarado</span><strong>${M(s.declared)}</strong></div><div class="receipt-line"><span>Diferencia</span><strong class="${q.difference?'negative':'positive'}">${M(q.difference)}</strong></div>${s.notes?`<p class="notes-box">${E(s.notes)}</p>`:''}`:''}<h3 class="section-label section-space">VENTAS DEL TURNO · ${q.sales.length}</h3>${q.sales.map(v=>`<button class="record" data-action="sale-detail" data-id="${E(v.id)}"><span class="record-icon">${Icon('sales')}</span><span><strong>${E(v.lines.map(l=>l.description).join(', '))}</strong><small>${dt(v.date)} · ${v.method}</small></span><span class="record-tail"><strong>${M(v.total)}</strong></span></button>`).join('')||'<p class="form-help">Sin ventas en este turno.</p>'}<h3 class="section-label section-space">OTROS MOVIMIENTOS</h3>${q.movements.map(m=>`<div class="receipt-line"><span>${E(m.concept)}<small>${dt(m.date)} · ${E(m.type)}</small></span><strong>${m.type==='Ingreso'?'+':'−'} ${M(m.amount)}</strong></div>`).join('')||'<p class="form-help">Sin movimientos adicionales.</p>'}<div class="modal-actions wrap-actions">${s.status==='Cerrada'?`<button class="btn btn-primary" data-action="pdf" data-id="${E(id)}">${Icon('download')} Descargar PDF</button>`:`${s.userId===actor().id?`<button class="btn btn-secondary" data-action="cash-move" data-id="${E(id)}">Movimiento</button>`:''}<button class="btn btn-primary" data-action="close-shift" data-id="${E(id)}">Cerrar caja</button>`}</div>`,true);}
  function employee(id){const e=state().employees.find(x=>x.id===id)||{};form(id?'Editar empleado':'Nuevo empleado','Define el acceso al sistema y el rol de la persona.',`<div class="form-grid">${field('Nombre completo','name',e.name,'text','required minlength="3"')}${field('Correo','email',e.email,'email','required')}${field('Usuario','username',e.username,'text','required minlength="3" autocomplete="off"')}${field(id?'Nueva contraseña (opcional)':'Contraseña','password','','password',`${id?'':'required'} minlength="6" autocomplete="new-password"`)}${select('Rol','role',option('receptionist','Recepcionista',e.role)+option('admin','Administrador',e.role))}${select('Estado','status',option('Activo','Activo',e.status)+option('Inactivo','Inactivo',e.status))}</div>`,v=>{O.saveEmployee(actor(),v,id);done('Acceso del empleado actualizado.');});}
  function handle(action,id){switch(action){case'new-booking':booking();break;case'edit-booking':booking(id);break;case'booking-detail':bookingDetail(id);break;case'book-room':booking(null,id);break;case'charge':sale(id);break;case'checkin':confirm('Registrar ingreso','Confirma que el huésped está entrando a su habitación.',()=>O.bookingAction(actor(),id,'checkin'));break;case'checkout':confirm('Registrar salida','La estancia se finalizará si su saldo está pagado.',()=>O.bookingAction(actor(),id,'checkout'));break;case'cancel-booking':confirm('Cancelar reserva','La habitación se liberará para estas fechas. Se conservará el historial.',()=>O.bookingAction(actor(),id,'cancel'));break;case'guest':guest(id);break;case'room':room(id);break;case'product':product(id);break;case'stock':stock(id);break;case'sale':sale();break;case'sell-product':sale('',id);break;case'sale-detail':saleDetail(id);break;case'open-shift':openShift();break;case'shift-detail':shiftDetail(id);break;case'cash-move':cashMove(id);break;case'close-shift':closeShift(id);break;case'employee':employee(id);break;case'pdf':try{CashPDF.download(id);H.toast('PDF de cierre descargado.');}catch(e){H.toast(e.message,'error');}break;}}
  document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el){Hotel.refresh();handle(el.dataset.action,el.dataset.id);}});
  return {booking,bookingDetail,guest,room,product,stock,sale,openShift,closeShift,shiftDetail,employee,show,dt,staff,field,select,option};
})();
