(() => {
  const H=Hotel, data=H.data;
  const today=H.offset(0);
  const roomPrice=r=>Number(r?.price ?? H.type(r?.type)?.price ?? 0);
  document.getElementById('year').textContent=new Date().getFullYear();
  const header=document.getElementById('site-header');
  const onScroll=()=>header.classList.toggle('scrolled',scrollY>40);
  addEventListener('scroll',onScroll,{passive:true});onScroll();
  const menu=document.getElementById('main-nav'), toggle=document.getElementById('menu-toggle');
  toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});
  menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
  const search=document.getElementById('availability-form');search.checkin.min=today;search.checkin.value=H.offset(1);search.checkout.min=H.offset(2);search.checkout.value=H.offset(3);search.checkin.addEventListener('change',()=>{search.checkout.min=H.offset(1);if(search.checkout.value<=search.checkin.value)search.checkout.value=new Date(new Date(`${search.checkin.value}T12:00:00`).getTime()+86400000).toISOString().slice(0,10)});
  document.getElementById('room-grid').innerHTML=data.roomTypes.map((room,i)=>`<article class="room-card"><div class="room-card-img"><img src="${room.image}" alt="${H.esc(room.name)}" loading="lazy"><span>${i===0?'EXPERIENCIA EXCLUSIVA':'AURIA HOTEL'}</span></div><div class="room-card-content"><h3>${H.esc(room.name)}</h3><div class="room-meta"><span>♙ ${room.capacity} huéspedes</span><span>◫ ${H.esc(room.bed)}</span><span>□ ${room.size} m²</span></div><div class="room-price"><strong>${H.money(room.price)}</strong><small>/ noche</small></div><div class="room-actions"><button class="text-link" data-room-detail="${room.id}">Ver habitación ↗</button><button class="btn btn-dark" data-book-type="${room.id}">Reservar ↗</button></div></div></article>`).join('');
  const services=[['♜','Restaurante','Sabores locales con una mirada contemporánea.'],['✧','Spa & bienestar','Un espacio para reconectar contigo.'],['≈','Piscina','Pausas tranquilas con vistas inolvidables.'],['⌁','Gimnasio','Tu rutina, también lejos de casa.'],['◉','Wi-Fi de alta velocidad','Conectividad en todos nuestros espacios.'],['◇','Servicio a la habitación','Atención personalizada a cualquier hora.'],['↗','Traslado al aeropuerto','Llegadas y partidas sin preocupaciones.'],['◷','Recepción 24/7','Siempre disponibles para acompañarte.']];
  document.getElementById('services-grid').innerHTML=services.map(([icon,title,description])=>`<div class="service-item"><div class="service-icon" aria-hidden="true">${icon}</div><h3>${title}</h3><p>${description}</p></div>`).join('');
  const gallery=[['Suite AURIA','https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&q=85'],['Lobby','https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=85'],['Restaurante','https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=85'],['Piscina','https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=85'],['Spa','https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=85']];
  document.getElementById('gallery-grid').innerHTML=gallery.map(([name,url],i)=>`<button class="gallery-item" data-gallery="${i}" aria-label="Ampliar imagen de ${name}"><img src="${url}" alt="${name} en AURIA" loading="lazy"><span>${name} ↗</span></button>`).join('');
  const quotes=[['Una experiencia impecable de principio a fin. La atención fue cálida y cada espacio invita a bajar el ritmo y disfrutar.','Mariana Torres','Santa Cruz, Bolivia'],['El equilibrio perfecto entre diseño y comodidad. Volvería a La Paz solo por disfrutar otra estancia aquí.','Santiago Rojas','Santiago, Chile'],['Despertar con esa luz, desayunar sin prisa y sentirse cuidado en cada detalle. Un lugar verdaderamente especial.','Isabella Moretti','Milán, Italia']];
  let quoteIndex=0;const renderQuote=()=>{const [text,name,place]=quotes[quoteIndex];document.getElementById('testimonial-card').innerHTML=`<div class="stars" aria-label="Cinco estrellas">★★★★★</div><blockquote>“${text}”</blockquote><div class="testimonial-person"><strong>${name}</strong><span>${place}</span></div>`};renderQuote();document.getElementById('testimonial-prev').onclick=()=>{quoteIndex=(quoteIndex+quotes.length-1)%quotes.length;renderQuote()};document.getElementById('testimonial-next').onclick=()=>{quoteIndex=(quoteIndex+1)%quotes.length;renderQuote()};
  const roomAvailable=(room,checkin,checkout)=>room.status!=='Mantenimiento'&&!data.reservations.some(r=>r.roomId===room.id&&['Confirmada','Pendiente'].includes(r.status)&&checkin<r.checkout&&checkout>r.checkin);
  const booking=(preferred='')=>{
    const checkin=search.checkin.value || H.offset(1),checkout=search.checkout.value || H.offset(3),guests=Number(search.guests.value)||2;
    if(checkin<today||H.nights(checkin,checkout)<1){H.toast('Selecciona fechas válidas para tu estancia.','error');return}
    const typeId=preferred||search.type.value;
    const available=data.rooms.filter(r=>roomAvailable(r,checkin,checkout)&&(!typeId||r.type===typeId)&&H.type(r.type)?.capacity>=guests);
    if(!available.length){H.toast('No hay habitaciones disponibles para esos criterios. Prueba otras fechas o categoría.','error');return}
    H.showModal(`<div class="modal-body"><button class="modal-close" data-close-modal aria-label="Cerrar">×</button><div class="eyebrow"><span></span> TU ESTANCIA EN AURIA</div><h2>Completa tu reserva</h2><p>Elige una habitación y confirma tus datos. No se realiza ningún cobro.</p><form class="modal-form" id="booking-form"><div class="form-grid"><label>Check-in<input name="checkin" type="date" min="${today}" value="${checkin}" required></label><label>Check-out<input name="checkout" type="date" min="${H.offset(1)}" value="${checkout}" required></label></div><div class="form-grid"><label>Huéspedes<select name="guests">${[1,2,3,4].map(n=>`<option value="${n}" ${n===guests?'selected':''}>${n} ${n===1?'huésped':'huéspedes'}</option>`).join('')}</select></label><label>Habitación<select name="roomId" required></select></label></div><div class="form-grid"><label>Nombre completo<input name="name" required minlength="3" placeholder="Tu nombre"></label><label>Correo electrónico<input type="email" name="email" required placeholder="tu@email.com"></label></div><label>Teléfono<input name="phone" type="tel" required minlength="7" placeholder="Tu número de contacto"></label><div class="booking-summary" id="booking-summary"></div><div class="modal-actions"><button class="btn btn-subtle" type="button" data-close-modal>Cancelar</button><button class="btn btn-dark" type="submit">Confirmar reserva ↗</button></div></form></div>`);
    const form=document.getElementById('booking-form');
    const refresh=()=>{const ci=form.checkin.value,co=form.checkout.value,g=Number(form.guests.value),options=data.rooms.filter(r=>roomAvailable(r,ci,co)&&H.type(r.type)?.capacity>=g);const select=form.roomId;const selected=select.value;select.innerHTML=options.map(r=>`<option value="${r.id}">${H.esc(H.type(r.type).name)} · ${r.number} · ${H.money(roomPrice(r))}/noche</option>`).join('');if(options.some(r=>r.id===selected))select.value=selected;else if(options.some(r=>r.id===available[0]?.id))select.value=available[0].id;const chosen=H.room(select.value),n=H.nights(ci,co);document.getElementById('booking-summary').innerHTML=chosen&&n>0?`<div><span>${n} ${n===1?'noche':'noches'} · ${H.esc(H.type(chosen.type).name)}</span><span>${H.money(roomPrice(chosen))}/noche</span></div><div><strong>Total estimado</strong><strong>${H.money(n*roomPrice(chosen))}</strong></div>`:'<span>No hay habitaciones disponibles para estos criterios.</span>';};
    form.querySelector('[name="roomId"]').addEventListener('change',refresh);['checkin','checkout','guests'].forEach(name=>form[name].addEventListener('change',refresh));refresh();
    form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),ci=f.get('checkin'),co=f.get('checkout'),g=Number(f.get('guests')),room=H.room(f.get('roomId'));if(ci<today||H.nights(ci,co)<1){H.toast('Revisa las fechas de la reserva.','error');return}if(!room||!roomAvailable(room,ci,co)||H.type(room.type).capacity<g){H.toast('Esa habitación ya no está disponible.','error');refresh();return}const name=String(f.get('name')).trim(),email=String(f.get('email')).trim().toLowerCase(),phone=String(f.get('phone')).trim();if(name.length<3||phone.length<7){H.toast('Completa tus datos de contacto.','error');return}let client=data.clients.find(c=>c.email.toLowerCase()===email);if(!client){client={id:H.uid('c'),name,email,phone,country:'No indicado'};data.clients.push(client)}const code=`AUR-${Date.now().toString(36).slice(-6).toUpperCase()}`;const total=H.nights(ci,co)*roomPrice(room);data.reservations.unshift({id:code,clientId:client.id,roomId:room.id,checkin:ci,checkout:co,guests:g,total,status:'Pendiente',created:today});H.save();H.showModal(`<div class="booking-success"><button class="modal-close" data-close-modal aria-label="Cerrar">×</button><div class="success-mark">✓</div><h2>¡Reserva recibida!</h2><p>Gracias, ${H.esc(name)}. Hemos registrado tu solicitud de estancia. Conserva este código para consultar con recepción.</p><div class="code">${code}</div><div class="booking-summary"><div><span>Habitación</span><strong>${H.esc(H.type(room.type).name)} · ${room.number}</strong></div><div><span>Fechas</span><strong>${H.date(ci)} – ${H.date(co)}</strong></div><div><span>Total estimado</span><strong>${H.money(total)}</strong></div></div><p>Esta es una demostración local. No se envió un correo ni se realizó ningún pago.</p><button class="btn btn-dark" data-close-modal>Entendido ↗</button></div>`);H.toast('Reserva creada correctamente.');});
  };
  search.addEventListener('submit',e=>{e.preventDefault();booking()});
  document.querySelectorAll('[data-open-booking]').forEach(btn=>btn.addEventListener('click',()=>booking()));
  document.getElementById('room-grid').addEventListener('click',e=>{const detail=e.target.closest('[data-room-detail]'),reserve=e.target.closest('[data-book-type]');if(detail){const r=H.type(detail.dataset.roomDetail);H.showModal(`<div class="room-detail-image"><img src="${r.image}" alt="${H.esc(r.name)}"></div><div class="modal-body"><button class="modal-close" data-close-modal aria-label="Cerrar">×</button><div class="eyebrow"><span></span> DESCANSA A TU RITMO</div><h2>${H.esc(r.name)}</h2><p>${H.esc(r.description)}</p><div class="room-detail-meta"><span>♙ Hasta ${r.capacity} huéspedes</span><span>◫ Cama ${H.esc(r.bed)}</span><span>□ ${r.size} m²</span></div><div class="room-actions"><span class="room-detail-price">${H.money(r.price)} <small>/ noche</small></span><button class="btn btn-dark" id="detail-book">Reservar ahora ↗</button></div></div>`);document.getElementById('detail-book').onclick=()=>booking(r.id)}if(reserve)booking(reserve.dataset.bookType)});
  document.getElementById('gallery-grid').addEventListener('click',e=>{const b=e.target.closest('[data-gallery]');if(!b)return;const [name,url]=gallery[Number(b.dataset.gallery)];H.showModal(`<button class="modal-close" data-close-modal aria-label="Cerrar">×</button><img class="lightbox-image" src="${url}" alt="${name} en AURIA"><div class="lightbox-caption">${name} · AURIA Hotel Boutique</div>`)});
  document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;document.getElementById('contact-feedback').textContent='Mensaje registrado en esta demostración. Gracias por escribirnos.';H.toast('Mensaje enviado correctamente.');form.reset()});
})();
